# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='目标城市')),
                ('minDistance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('maxDistance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('minDatingAge', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('maxDatingAge', models.IntegerField(default=45, verbose_name='最大交友年龄')),
                ('datingSex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=8, verbose_name='匹配的性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('onlyMat', models.BooleanField(default=True, verbose_name='不让未匹配的人看我的相册')),
                ('autoPlay', models.BooleanField(default=True, verbose_name='是否自动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=32, unique=True)),
                ('phoneNum', models.CharField(max_length=16, unique=True)),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=8)),
                ('birthYear', models.IntegerField()),
                ('birthMonth', models.IntegerField()),
                ('birthDay', models.IntegerField()),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
